#import "/DarkFactory/schema.typ": folder

// Intentionally empty. This slot is reserved for canonical autogenerated
// DarkFactory documentation rather than hand-maintained thesis prose.
#let node = folder(
  key: "darkfactory",
  title: [DarkFactory],
)
