#import "/DarkFactory/schema.typ": folder

// Reserved for the full canonical autogenerated DarkFactory documentation.
// Hand-maintained architecture/lifecycle prose intentionally does not live here.
#let node = folder(
  key: "darkfactory",
  title: [DarkFactory],
)
