#import "/DarkFactory/templates/common.typ": bib
#import "/DarkFactory/schema.typ": section

#let item = section(
  key: "change_interruption_recovery_body",
  title: [Přerušení a obnova],
  definition: terms => [
Přerušení běhu nesmí samo o sobě způsobit opakování již potvrzených účinků ani ztrátu rozhodujícího pracovního stavu.
  ],
  description: terms => [
DarkFactory proto váže pokračování na persistovaný stav a kontrolu jeho původu a aktuálnosti. Detailní mechanismus Recovery bude vlastněn kanonickou autogenerated dokumentací DarkFactory v části 3.2; zde je uvedena pouze jeho role v životním cyklu změny. #cite(bib.darkfactory)
  ],
)
