#import "/DarkFactory/templates/common.typ": bib
#import "/DarkFactory/schema.typ": section

#let item = section(
  key: "change_interruption_recovery_body",
  title: [Přerušení a obnova],
  definition: terms => [
Přerušený životní cyklus se nevrací automaticky na začátek; pokračování musí navázat na poslední potvrzený stav změny.
  ],
  description: terms => [
Konkrétní Recovery mechanismus patří do kanonické autogenerated dokumentace DarkFactory v části 3.2. Z pohledu životního cyklu je podstatné pouze to, že obnovení nesmí znovu provést již potvrzený účinek ani přijmout stav, jehož původ nebo aktuálnost už nelze doložit. #cite(bib.darkfactory)
  ],
)
